version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: monthly
